### ISSUE TITLE
Add creeps

### ISSUE THREAD

**Issue by Jeinhaus** [Jeinhaus/TowerDefense#1]
We should add creeps so we have something to shoot at 💃 
They should:
- spawn at a defined location
- move
- have defined hp
- die when hp reaches 0

**Comment by SolidPlayer** [comment]
Create supersized Ant-model for creep

**Comment by Jeinhaus** [comment]
Added creeps on last commit [66968b2](https://github.com/Jeinhaus/TowerDefense/commit/66968b2949084b8c76f64ada0f46b8489a70b67b)
